# Generated by Django 4.1 on 2022-08-16 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='buy_at',
        ),
    ]
