# Generated by Django 4.1 on 2022-08-18 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_about_categoriya_what_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='phone',
        ),
    ]
